name: Pin-Up Geek
markdown: redcarpet
pygments: true
permalink: /:title
paginate: 10
paginate_path: "page:num"
excerpt_separator: "<!--more-->"
description: "Ruby on Rails blog by Christopher Davis"
url: http://www.pinupgeek.com
